---

- name: 'update aliases databases'  # noqa 503
  command: newaliases
  when: __opensmtpd_aliases_result.changed

- name: 'update list-formatted tables'
  template:
    src: 'etc/mail/tables_list.j2'
    dest: "{{ item.value.path }}"
    owner: 'root'
    group: "{{ _opensmtpd_root_group }}"
    mode: '0644'
  register: __opensmtpd_tables_list_result
  loop: "{{ lookup('dict', opensmtpd_tables_list, wantlist=True) }}"

- name: 'update list-formatted databases'  # noqa 503
  command: |
    makemap -t set {{ item.item.value.makemap }}.db
  when: >
    item.changed
    and item.item.value.makemap | default(False) | bool
  loop: "{{ __opensmtpd_tables_list_result.results }}"

- name: 'update mappings-formatted tables'
  template:
    src: 'etc/mail/tables_mappings.j2'
    dest: "{{ item.value.path }}"
    owner: 'root'
    group: "{{ _opensmtpd_root_group }}"
    mode: '0644'
  register: __opensmtpd_tables_mappings_result
  loop: "{{ lookup('dict', opensmtpd_tables_mappings, wantlist=True) }}"

- name: 'update mappings-formatted databases'  # noqa 503
  command: |
    makemap -t aliases {{ item.item.value.makemap }}.db
  when: >
    item.changed
    and item.item.value.makemap | default(False) | bool
  loop: "{{ __opensmtpd_tables_mappings_result.results }}"

- name: 'install the opensmtpd config file'
  template:
    src: 'etc/mail/smtpd.conf.j2'
    dest: "{{ _opensmtpd_conf_path }}"
    owner: 'root'
    group: "{{ _opensmtpd_root_group }}"
    mode: '0644'
    validate: "{{ _opensmtpd_bin_name }} -n -f %s"
  notify:
    - 'opensmtpd_restart_handler'
