---

- name: gather data about services
  service_facts:

- name: disable mailer services
  service:
    name: "{{ item.name }}"
    state: stopped
    enabled: False
  when: >
    ansible_facts['services'][item.name + '.service'] is defined
  loop: "{{ opensmtpd_mailers_to_remove }}"

- name: mask mailer services
  systemd:
    name: "{{ item.name }}"
    masked: True
  when: >
    ansible_facts['service_mgr'] == 'systemd'
    and ansible_facts['services'][item.name + '.service'] is defined
  loop: "{{ opensmtpd_mailers_to_remove }}"

- include_role:
    name: t18s.fr_pkg
  vars:
    pkg_list: "{{ opensmtpd_mailers_to_remove | json_query(\"[*].packages | [].{ name: name, state: 'absent' }\") }}"
