---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_maildir_by_os_family:
      Debian: '/home/testinfra/Maildir'
      OpenBSD: '/var/mail/testinfra'

  tasks:
    - name: 'Try to send mail'
      shell: |
        echo 'content' | mail -s 'title' root@localhost
      register: __verify_mail
      failed_when: not __verify_mail.rc == 0

    - name: 'Check maildir exists'
      stat:
        path: "{{ __verify_maildir_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_maildir
      failed_when: not __verify_maildir.stat.exists
