---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_service_name_by_os_distribution:
      Debian: 'opensmtpd'
      OpenBSD: 'smtpd'

    __verify_maildir_by_os_family:
      Debian: '/home/testinfra/Maildir'
      OpenBSD: '/var/mail/testinfra'

  tasks:
    - name: 'Check the service is enabled/started'
      service:
        name: "{{ __verify_service_name_by_os_distribution[ ansible_facts['os_family'] ] }}"
        enabled: True
        state: 'started'
      register: __verify
      failed_when: __verify.changed

    - name: 'Try to send mail'
      shell: |
        echo 'content' | mail -s 'title' root@localhost
      register: __verify_mail
      failed_when: not __verify_mail.rc == 0

    - name: 'Check maildir exists'
      stat:
        path: "{{ __verify_maildir_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_maildir
      failed_when: not __verify_maildir.stat.exists
